### DISCUSSION TITLE
Frontend Unable to Connect to Backend in Kubernetes and Docker Deployments: Requests Default to Localhost

### DISCUSSION THREAD

**Discussion by nick1ee** [RamiAwar/dataline#293] [Q&A] [answered]
We attempted to deploy Dataline to our Kubernetes environment, but it’s not working as expected. It appears that I can access the frontend through the custom domain, but the connections from the frontend are being blocked.

The frontend is trying to send requests to http://localhost:7377 for health checks and other operations.

We also tried running Dataline on a VM using docker run and accessed the web interface via the VM’s IP address. The result was the same: we could reach the frontend, but the frontend couldn’t connect to the backend, as it was still trying to send requests to localhost.

Additionally, we tried setting the ALLOW_ORIGINS environment variable to include our custom domain, but it doesn’t seem to have any effect.

How can I change the default domain for the backend? It should match the custom domain I use to access the frontend, rather than defaulting to localhost.

![dataline-screenshot](https://github.com/user-attachments/assets/a0e9c5d1-3212-4083-91d2-470e710e1ad3)

**Comment by RamiAwar** [comment]
There's a frontend variable for the backend host as well!

Set "VITE_API_URL" to point to your backend.

We might not have documented I'll double check.

Allowed origins is only important to set if you're using authentication.

Let me know if that works!

**Reply by nick1ee** [reply]
We discovered the following logic in source code:

`export const apiURL = import.meta.env.VITE_API_URL || "http://localhost:7377";`

We tried setting the VITE_API_URL environment variable both by using the -e flag with docker run and through a ConfigMap in our Kubernetes deployment. However, the newly deployed frontend still attempts to send requests to localhost, indicating that the configuration change didn’t take effect.

**Reply by RamiAwar** [reply]
Ah I see the issue. I assume you're using Docker then, the docker env var is called "API_URL". That in turn gets turned into VITE_API_URL in the dockerfile 

```
ARG API_URL="http://localhost:7377"

ENV VITE_API_URL=$API_URL
```

Thanks for bringing this up, it needs more documentation on our end. LMK if this works

**Reply by Pin-Jui** [reply]
I’m Nick’s colleague.
We tried the following two configurations, but we are still facing the same issue:

`docker run -p 7377:7377 -v dataline:/home/.dataline --name dataline-external -e API_URL="http://EXTERNAL_IP:7377/" ramiawar/dataline:latest`

`docker run -p 7377:7377 -v dataline:/home/.dataline --name dataline-external -e API_URL="http://0.0.0.0:7377/" ramiawar/dataline:latest`

**Reply by RamiAwar** [reply]
I see.. Can you share more about your kubernetes config? I think the problem lies there.

**Reply by RamiAwar** [reply]
In the first line you sent, is EXTERNAL_IP a bash variable?

**Reply by Pin-Jui** [reply]
We run these commands on GCP VM instead of GKE to test ENV, but still the same
`docker run -p 7377:7377 -v dataline:/home/.dataline --name dataline-external ramiawar/dataline:latest`

This is our GKE statefulset config:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dataline
  namespace: dataline
  labels:
    app: dataline
spec:
  serviceName: "dataline"
  replicas: 1
  selector:
    matchLabels:
      app: dataline
  template:
    metadata:
      labels:
        app: dataline
    spec:
      containers:
        - image: ramiawar/dataline:latest
          name: dataline
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7377
              name: backend
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
          livenessProbe:
            httpGet:
              path: /
              port: 7377
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 7377
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /home/.dataline
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

```
